---
kubernetes_gpgkey: "https://packages.cloud.google.com/apt/doc/apt-key.gpg"
kubernetes_repository: "deb https://apt.kubernetes.io/ kubernetes-xenial main"
cri_socket: "unix:///var/run/cri-dockerd.sock"
