---
# https://docs.docker.com/install/linux/docker-ce/ubuntu/

- name: install pre-requisites
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common

- name: add apt key
  apt_key:
    url: "{{ docker_gpgkey }}"
    state: present

- name: add apt repo
  apt_repository:
    repo: "{{ docker_repository }}"
    state: present
    update_cache: true

- name: config directory
  file:
    path: /etc/docker
    state: directory
    owner: root
    group: root
    mode: 0755

- name: config file
  copy:
    src: daemon.json
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: 0644

- name: install packages
  apt:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io

# https://kubernetes.io/blog/2020/12/02/dockershim-faq/

- name: set dpkg_arch
  set_fact:
    dpkg_arch: amd64
    cacheable: yes
  when: ansible_architecture == "x86_64"

- name: set dpkg_arch
  set_fact:
    dpkg_arch: arm64
    cacheable: yes
  when: ansible_architecture == "aarch_64"

- name: install packages
  apt:
    deb: "{{ cri_dockerd_deb_url }}"
    state: present

# https://docs.docker.com/engine/install/linux-postinstall/

- name: add user to docker group
  user:
    name='{{ item }}'
    groups=docker
    append=yes
  with_items:
    "{{ ansible_user }}"
