---
# https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/

- name: install pre-requisites
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common

- name: add apt key
  apt_key:
    url: "{{ kubernetes_gpgkey }}"
    state: present

- name: add apt repo
  apt_repository:
    repo: "{{ kubernetes_repository }}"
    state: present
    update_cache: true

- name: kubeadm config file
  template:
    src: config.yaml.j2
    dest: kubeadm-config.yaml

- name: cri config file
  template:
    src: crictl.yaml.j2
    dest: /etc/crictl.yaml
    owner: root
    group: root
    mode: 0644

- name: cni config directory
  file:
    path: /etc/cni/net.d
    state: directory
    owner: root
    group: root
    mode: 0755

- name: cni config file
  copy:
    src: 10-docker-net.conflist
    dest: /etc/cni/net.d/10-docker-net.conflist
    owner: root
    group: root
    mode: 0644

- name: install packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - kubeadm={{ k8s_version }}*
      - kubelet={{ k8s_version }}*
      - kubectl={{ k8s_version }}*
      - cri-tools={{ cri_version }}*
      - kubernetes-cni={{ cni_version }}*

# See https://github.com/ansible/ansible-modules-core/issues/19 (from 2014)

- name: show hold
  command: apt-mark showhold
  register: held_packages
  changed_when: false

- name: hold packages
  shell: apt-mark hold {{ item }}
  changed_when: "item not in held_packages.stdout"
  with_items:
    - kubeadm
    - kubelet
    - kubectl
