---
# https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/

- name: install pre-requisites
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common

- name: add apt key
  apt_key:
    url: "{{ kubernetes_gpgkey }}"
    state: present

- name: add apt repo
  apt_repository:
    repo: "{{ kubernetes_repository }}"
    state: present
    update_cache: true

- name: config directory
  file:
    path: /var/lib/kubelet
    state: directory
    owner: root
    group: root
    mode: 0755

- name: config file
  copy:
    src: config.yaml
    dest: /var/lib/kubelet/config.yaml
    owner: root
    group: root
    mode: 0644

- name: install packages
  apt:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - kubeadm
      - kubelet
      - kubectl

# See https://github.com/ansible/ansible-modules-core/issues/19 (from 2014)

- name: show hold
  command: apt-mark showhold
  register: held_packages
  changed_when: false

- name: hold packages
  shell: apt-mark hold {{ item }}
  changed_when: "item not in held_packages.stdout"
  with_items:
    - kubeadm
    - kubelet
    - kubectl

- debug: msg="{{ list.stdout.splitlines() }}"

- name: images load
  shell: |
    test -e /images/images.tgz && zcat /images/images.tgz | docker load

- name: images pull
  shell: kubeadm config images pull

- name: images save
  shell: |
    test -e /images/images.tgz || kubeadm config images list | xargs docker save | gzip -9 > /images/images.tgz
    kubeadm config images list > /images/images.txt
